/*
 * K2-BackEnd API
 *
 * K2のバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "k2-backend/go"

	"github.com/rs/cors"
	lumberjack "gopkg.in/natefinch/lumberjack.v2"
)

func main() {

	log.SetOutput(&lumberjack.Logger{
		Filename:   "./logs/system.log",
		MaxSize:    100, // megabytes
		MaxBackups: 10,
		MaxAge:     28, //days
		Compress:   true,
	})

	log.Printf("Server started")

	router := sw.NewRouter()
	c := cors.Default().Handler(router)

	log.Fatal(http.ListenAndServe(":60001", c))
}
