/*
 * K2-BackEnd API
 *
 * K2のバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"
)

func AggregationGet(w http.ResponseWriter, r *http.Request) {
	getAggregationFunc(w, r)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func BudgetGet(w http.ResponseWriter, r *http.Request) {
	getBudgetFunc(w, r)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func BudgetPost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	postBudgetFunc(w, r)

}

func PerformanceGet(w http.ResponseWriter, r *http.Request) {
	getPerformanceFunc(w, r)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func PerformancePost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
}

func AccountMasterGet(w http.ResponseWriter, r *http.Request) {
	getAccountMasterFunc(w, r)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
