/*
 * K2-BackEnd API
 *
 * K2のバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PostDitailInner struct {

	Year string `json:"year"`

	Month string `json:"month"`

	Account string `json:"account"`

	Amount int64 `json:"amount,omitempty"`
}
