/*
 * K2-BackEnd API
 *
 * K2のバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccountMasterBody struct {

	AccountData []AccountMaster `json:"account_data,omitempty"`
}
