/*
 * K2-BackEnd API
 *
 * K2のバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Performance struct {
	Account string `json:"account"`

	Amount int64 `json:"amount"`

	Balance int64 `json:"balance"`
}
