/*
 * K2-BackEnd API
 *
 * K2のバックエンドAPI
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Aggregation struct {

	Budget int64 `json:"budget"`

	Consum int64 `json:"consum"`

	Balance int64 `json:"balance"`
}
